# Generated by Django 5.2.10 on 2026-01-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Design name for identification', max_length=100)),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='ticket_templates/')),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('checkin_reward_image', models.ImageField(blank=True, help_text='Image to be sent as NFT reward after check-in completion', null=True, upload_to='ticket_templates/checkin_rewards/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_system_ticket_design',
                'indexes': [models.Index(fields=['is_active'], name='idx_ticket_design_active')],
            },
        ),
    ]
