# Generated by Django 5.2.12 on 2026-03-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_service', '0006_ticketcheckinurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdesign',
            name='layout_html',
            field=models.TextField(blank=True, help_text='HTML template for ticket layout (placeholders: {{ event_name }}, {{ event_date }}, {{ venue }}, {{ seat }}, {{ holder_paymail }}, {{ background_block }}, {{ qr_block }}, {{ nft_metadata_json }})', null=True),
        ),
    ]
