"""
Django settings for ticket_system project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv, dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# Docker compose mounts .env into /home/app/.env, so use BASE_DIR.parent
ENV_DIR = BASE_DIR.parent
dotenv_path = os.path.join(ENV_DIR, ".env")
env_local_path = os.path.join(ENV_DIR, "env.local")

# Load primary first, then local overrides (if any).
load_dotenv(dotenv_path)
if os.path.exists(env_local_path):
    load_dotenv(env_local_path, override=True)

# Some env files in this repo use "KEY = value" (spaces around '=') and/or quotes.
# `load_dotenv()` usually handles it, but to be robust we also read parsed values
# directly and use them as a fallback when os.environ doesn't contain a key.
_DOTENV_VALUES = dict(dotenv_values(dotenv_path))
if os.path.exists(env_local_path):
    _DOTENV_VALUES.update(dotenv_values(env_local_path))


def _get_env(key: str, default=None):
    """
    環境変数を取得（.envファイルからも読み込み）

    Args:
        key: 環境変数名
        default: デフォルト値

    Returns:
        環境変数の値、またはデフォルト値
    """
    val = os.environ.get(key)
    if val is not None and val != "":
        return val
    for k in (key, key.strip(), f"{key} ", f" {key}"):
        v = _DOTENV_VALUES.get(k)
        if v is not None and v != "":
            return v
    return default

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY = os.environ.get('SECRET_KEY', '') or _get_env('SECRET_KEY', '')
SECRET_KEY = _SECRET_KEY if _SECRET_KEY.strip() else 'django-insecure-change-me-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS: DOMAIN_NAME（サーバのFQDN）を優先。未設定時は ALLOWED_HOSTS またはデフォルト
_DOMAIN_NAME = _get_env('DOMAIN_NAME', '').strip()
if _DOMAIN_NAME:
    _hosts = [h.strip() for h in _DOMAIN_NAME.split(',') if h and h.strip()]
    _hosts.extend(['localhost', '127.0.0.1'])
    ALLOWED_HOSTS = list(dict.fromkeys(_hosts))  # 重複除去・順序保持
else:
    _ALLOWED_HOSTS = _get_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')
    ALLOWED_HOSTS = [h.strip() for h in _ALLOWED_HOSTS.split(',') if h and h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'ticket_service',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ticket_system.urls'

# CORS: Swagger UI "Try it out" from browser (localhost / 127.0.0.1)
# DEBUG 時は任意オリジンを許可（WSL・別IPで開く場合も動くようにする）
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8001',
        'http://127.0.0.1:8001',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]
CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ticket_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_use_sqlite = os.environ.get('USE_SQLITE', '').lower() in ('1', 'true', 'yes')
if _use_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('SQL_DATABASE', 'ticket_system'),
            'USER': os.environ.get('SQL_USER', 'postgres'),
            'PASSWORD': os.environ.get('SQL_PASSWORD', 'postgres'),
            'HOST': os.environ.get('SQL_HOST', 'ticket_db'),
            'PORT': os.environ.get('SQL_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# OpenAPI (drf-spectacular) settings
# POSTPROCESSING_HOOK でリクエストのオリジンを SERVERS に注入し、Swagger UI の「Try it out」を同一オリジンにする（Failed to fetch 対策）
SPECTACULAR_SETTINGS = {
    'TITLE': 'Ticket Extension API',
    'DESCRIPTION': 'API for ticket image generation and check-in.',
    'VERSION': 'v1',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVERS': [{'url': '/', 'description': 'Current origin (fallback)'}],
    'POSTPROCESSING_HOOKS': [
        'ticket_system.schema_hooks.inject_servers_from_request',
        'drf_spectacular.hooks.postprocess_schema_enums',
    ],
}

# Login URL for Swagger UI (used by apiLogin() function)
LOGIN_URL = '/accounts/login/'

# Session settings (compatible with BETAWALLET-DEV)
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True') == 'True'  # HTTPS使用時
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN', None)  # .buxbit.net for cross-subdomain sharing
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Base API URL
# .envファイルに以下を追加:
# BASE_API_URL=http://localhost:8000
BASE_API_URL = _get_env('BASE_API_URL', 'http://localhost:8000')
# ベースAPIが自己署名証明書の場合は False にする（例: BASE_API_VERIFY_SSL=0）
_base_verify = os.environ.get('BASE_API_VERIFY_SSL', 'True').lower()
BASE_API_VERIFY_SSL = _base_verify in ('1', 'true', 'yes')

# CSRF settings
_CSRF_TRUSTED = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:1338,https://localhost:5443',
).split(',')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _CSRF_TRUSTED if o and o.strip()]
if 'https://ticket.buxbit.net' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append('https://ticket.buxbit.net')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True') == 'True'  # HTTPS使用時
CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN', None)  # .buxbit.net for cross-subdomain sharing
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False

# Trust proxy headers for HTTPS when behind Nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
